# Generated by Django 4.2.4 on 2023-10-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0002_usuario_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
