# Generated by Django 4.2.6 on 2023-10-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0002_profile_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
