# Generated by Django 4.2.6 on 2023-11-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('obra', '0003_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Consultor', 'Consultor')], default='Consultor', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(related_name='usuarios', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(related_name='usuarios', to='auth.permission'),
        ),
    ]
